package com.example.demo.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wx
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Wx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.wnum
     *
     * @mbg.generated
     */
    private String wnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.id
     *
     * @return the value of wx.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.id
     *
     * @param id the value for wx.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.wnum
     *
     * @return the value of wx.wnum
     *
     * @mbg.generated
     */
    public String getWnum() {
        return wnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.wnum
     *
     * @param wnum the value for wx.wnum
     *
     * @mbg.generated
     */
    public void setWnum(String wnum) {
        this.wnum = wnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.phone
     *
     * @return the value of wx.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.phone
     *
     * @param phone the value for wx.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.ctime
     *
     * @return the value of wx.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.ctime
     *
     * @param ctime the value for wx.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}